name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3

    - name: Go mod download + build
      run: cd cmd/twc-app && go mod download && go build -v ./...

    - name: ls current wd
      run: pwd

    - name: Run tests and coverage
      run: cd cmd/twc-app && go test -race -coverprofile=${{github.workspace}}/coverage.out -covermode=atomic -v ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true