name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3

    - name: Build
      run: go build -v ./cmd/twc-app/main.go

    - name: Run tests and coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic -v twc-app/...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}