name: terraform

on:
  push:
    branches: 
      - master 
    pull_request: 
env:
  AWS_REGION: ap-southeast-1
permissions:
  id-token: write
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::761953531066:role/github-action-man
        aws-region: ${{ env.AWS_REGION }}

    - name: Configure terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Terraform configurations and validation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./terraform
      run: |
        cat > terraform.tfvars <<EOF
        database_user = "${{ secrets.DATABASE_USER }}"
        database_host = "${{ secrets.DATABASE_HOST }}"
        database_password = "${{ secrets.DATABASE_PASSWORD }}"
        database_root_password = "${{ secrets.DATABASE_ROOT_PASSWORD }}"
        volume_mount_path = "${{ secrets.VOLUME_MOUNT_PATH }}"
        upload_mount_path = "${{ secrets.UPLOAD_MOUNT_PATH }}"
        ssl_pem = "${{ secrets.SSL_PEM }}"
        ssl_key = "${{ secrets.SSL_KEY }}"
        signature_key = "${{ secrets.SIGNATURE_KEY }}"
        env = "${{ secrets.ENV }}"
        EOF
        terraform init
        terraform validate
        terraform plan