name: Terraform validator and planner

on:
  push:
    branches: 
      - master 
    pull_request: 

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: terraform confiugrations and validation
      working-directory: ./terraform
      run: |
        terraform init
        terraform validate
        terraform plan