name: Terraform validator and planner

on:
  push:
    branches: 
      - master 
    pull_request: 

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: terraform init
      run: terraform init
    
    - name: terraform validate
      run: terraform validate
    
    - name: terraform plan
      run: terraform plan